title: "Wyatt King"
description: "Senior at Columbia University"

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown

logo: PANA60103.jpg

nav:
  - name: "Home"
    link: /
  - name: "CV"
    link: /cv/

show_excerpts: true
